apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Parsers_File parsers.conf

    [INPUT]
        Name tail
        Path /var/log/containers/*flask-app*.log
        Tag flask
        Parser docker
        Refresh_Interval 5

    [FILTER]
        Name parser
        Match flask
        Key_Name log
        Parser flask_json
        Reserve_Data On
        Preserve_Key Off

    [FILTER]
        Name modify
        Match flask
        Add source fluent-bit-parsed

    [OUTPUT]
        Name es
        Match *
        Host elasticsearch.logging.svc.cluster.local
        Port 9200
        Index flask-logs
        Logstash_Format On
        Logstash_Prefix flask-logs
        Suppress_Type_Name On

  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [PARSER]
        Name flask_json
        Format json
        Time_Key timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ