apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  index-template.json: |
    {
      "index_patterns": ["fluentbit-*", "logs-*"],
      "template": {
        "settings": {
          "number_of_shards": 1,
          "number_of_replicas": 0,
          "index.refresh_interval": "5s"
        },
        "mappings": {
          "properties": {
            "@timestamp": {
              "type": "date"
            },
            "timestamp": {
              "type": "date"
            },
            "level": {
              "type": "keyword"
            },
            "message": {
              "type": "text"
            },
            "component": {
              "type": "keyword"
            },
            "kubernetes": {
              "properties": {
                "namespace_name": {"type": "keyword"},
                "pod_name": {"type": "keyword"},
                "container_name": {"type": "keyword"}
              }
            }
          }
        }
      }
    }
