apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30200
      name: http
    - port: 9300
      targetPort: 9300
      nodePort: 30300
      name: transport
  selector:
    app: elasticsearch