apiVersion: v2
name: fluent-bit
description: A Helm chart for Fluent Bit log processor and forwarder
type: application
version: 0.1.0
appVersion: "2.2.0"
keywords:
  - fluent-bit
  - logging
  - log-processor
  - efk
  - daemonset
home: https://fluentbit.io/
sources:
  - https://github.com/fluent/fluent-bit
maintainers:
  - name: marboccu
    email: marboccu@lol.it
annotations:
  category: Logging