apiVersion: v2
name: elasticsearch
description: A Helm chart for Elasticsearch optimized for local development
type: application
version: 0.1.0
appVersion: "8.11.0"
keywords:
  - elasticsearch
  - search
  - logging
  - efk
home: https://www.elastic.co/elasticsearch/
sources:
  - https://github.com/elastic/elasticsearch
maintainers:
  - name: marboccu
    email: marboccu@lol.it
annotations:
  category: Database